// File overview: IMAP primitives used by copy-only remote synchronization.

package imapclient

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"

	"rolltop/backend/store"
	"rolltop/backend/syncer"
)

// SyncMarkerHeader identifies a source message after it has been appended to a
// destination server. The value is deterministic for one task and source UID.
const SyncMarkerHeader = "X-Rolltop-Sync-ID"

// MailboxUIDSearch is a stable source-mailbox snapshot plus the UIDs selected
// for a copy pass.
type MailboxUIDSearch struct {
	UIDValidity uint32
	UIDNext     uint32
	UIDs        []uint32
}

// SyncDestinationSession owns one authenticated, selected destination mailbox
// for a copy run. Its methods must be called sequentially; go-imap does not
// permit overlapping commands on one client connection.
type SyncDestinationSession struct {
	fetcher *Fetcher
	client  *client.Client
	mailbox string
}

// OpenSyncDestinationSession logs in and selects one destination mailbox once,
// allowing a large copy run to reuse the same TLS and IMAP session.
func (f *Fetcher) OpenSyncDestinationSession(ctx context.Context, account store.MailAccount, mailbox string) (*SyncDestinationSession, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if f == nil {
		return nil, errors.New("open sync destination session requires a fetcher")
	}
	mailbox = strings.TrimSpace(mailbox)
	if mailbox == "" {
		return nil, errors.New("open sync destination session requires a mailbox name")
	}
	c, err := f.login(account)
	if err != nil {
		return nil, err
	}
	if _, err := c.Select(mailbox, true); err != nil {
		_ = c.Logout()
		return nil, fmt.Errorf("select mailbox %q read-only for sync destination: %w", mailbox, err)
	}
	if err := ctx.Err(); err != nil {
		_ = c.Logout()
		return nil, err
	}
	return &SyncDestinationSession{fetcher: f, client: c, mailbox: mailbox}, nil
}

// Close logs out of the held destination connection. It is safe to call more
// than once after all session operations have stopped.
func (s *SyncDestinationSession) Close() error {
	if s == nil || s.client == nil {
		return nil
	}
	c := s.client
	s.client = nil
	return c.Logout()
}

func (s *SyncDestinationSession) ready(ctx context.Context) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if s == nil || s.client == nil || s.fetcher == nil || strings.TrimSpace(s.mailbox) == "" {
		return errors.New("sync destination session is closed")
	}
	return nil
}

// SearchMailboxUIDsSince selects one mailbox read-only and searches for UIDs
// newer than afterUID whose IMAP internal date is on or after since. A zero
// since value disables the date constraint.
func (f *Fetcher) SearchMailboxUIDsSince(ctx context.Context, account store.MailAccount, mailbox string, afterUID uint32, since time.Time) (MailboxUIDSearch, error) {
	select {
	case <-ctx.Done():
		return MailboxUIDSearch{}, ctx.Err()
	default:
	}
	mailbox = strings.TrimSpace(mailbox)
	if mailbox == "" {
		return MailboxUIDSearch{}, errors.New("search mailbox requires a mailbox name")
	}
	c, err := f.login(account)
	if err != nil {
		return MailboxUIDSearch{}, err
	}
	defer c.Logout()
	selected, err := c.Select(mailbox, true)
	if err != nil {
		return MailboxUIDSearch{}, fmt.Errorf("select mailbox %q read-only for UID search: %w", mailbox, err)
	}
	out := MailboxUIDSearch{}
	if selected != nil {
		out.UIDValidity = selected.UidValidity
		out.UIDNext = selected.UidNext
	}
	criteria, ok := mailboxUIDSearchCriteria(afterUID, since)
	if !ok || selected == nil || selected.Messages == 0 || (selected.UidNext > 0 && selected.UidNext <= afterUID+1) {
		return out, nil
	}
	uids, err := c.UidSearch(criteria)
	if err != nil {
		return MailboxUIDSearch{}, fmt.Errorf("search mailbox %q after UID %d: %w", mailbox, afterUID, err)
	}
	out.UIDs = normalizeUIDList(uids)
	return out, nil
}

func mailboxUIDSearchCriteria(afterUID uint32, since time.Time) (*imap.SearchCriteria, bool) {
	if afterUID == ^uint32(0) {
		return nil, false
	}
	criteria := imap.NewSearchCriteria()
	criteria.Uid = new(imap.SeqSet)
	criteria.Uid.AddRange(afterUID+1, 0)
	if !since.IsZero() {
		criteria.Since = since
	}
	return criteria, true
}

// MessageSyncMarker returns the deterministic marker for one source UID. Task
// tokens are generated by the caller and must contain only identifier-safe
// characters so the result is safe to place in an RFC 5322 header.
func MessageSyncMarker(taskToken string, uidValidity, uid uint32) (string, error) {
	var err error
	taskToken, err = validateSyncTaskToken(taskToken)
	if err != nil {
		return "", err
	}
	if uidValidity == 0 || uid == 0 {
		return "", errors.New("sync marker requires nonzero UIDVALIDITY and UID")
	}
	return fmt.Sprintf("v1.%s.%010d.%010d", taskToken, uidValidity, uid), nil
}

func validateSyncTaskToken(taskToken string) (string, error) {
	taskToken = strings.TrimSpace(taskToken)
	if taskToken == "" {
		return "", errors.New("sync marker requires a task token")
	}
	if len(taskToken) > 128 {
		return "", errors.New("sync marker task token is too long")
	}
	for _, r := range taskToken {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			continue
		}
		return "", errors.New("sync marker task token contains invalid characters")
	}
	return taskToken, nil
}

// AddSyncMarkerHeader prepends a marker header without otherwise reserializing
// the source message. Calling it again with the same marker is idempotent.
func AddSyncMarkerHeader(raw []byte, marker string) ([]byte, error) {
	if len(raw) == 0 {
		return nil, errors.New("sync marker requires a raw message")
	}
	marker, err := validateSyncMarker(marker)
	if err != nil {
		return nil, err
	}
	if hasSyncMarkerHeader(raw, marker) {
		return append([]byte(nil), raw...), nil
	}
	lineEnding := []byte("\r\n")
	if firstLF := bytes.IndexByte(raw, '\n'); firstLF >= 0 && (firstLF == 0 || raw[firstLF-1] != '\r') {
		lineEnding = []byte("\n")
	}
	prefix := make([]byte, 0, len(SyncMarkerHeader)+2+len(marker)+len(lineEnding))
	prefix = append(prefix, SyncMarkerHeader...)
	prefix = append(prefix, ':', ' ')
	prefix = append(prefix, marker...)
	prefix = append(prefix, lineEnding...)
	out := make([]byte, 0, len(prefix)+len(raw))
	out = append(out, prefix...)
	out = append(out, raw...)
	return out, nil
}

func validateSyncMarker(marker string) (string, error) {
	marker = strings.TrimSpace(marker)
	if marker == "" {
		return "", errors.New("sync marker is required")
	}
	if len(marker) > 240 {
		return "", errors.New("sync marker is too long")
	}
	for _, r := range marker {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' || r == '.' {
			continue
		}
		return "", errors.New("sync marker contains invalid characters")
	}
	return marker, nil
}

func hasSyncMarkerHeader(raw []byte, marker string) bool {
	headerEnd := len(raw)
	if i := bytes.Index(raw, []byte("\r\n\r\n")); i >= 0 {
		headerEnd = i
	} else if i := bytes.Index(raw, []byte("\n\n")); i >= 0 {
		headerEnd = i
	}
	for _, line := range bytes.Split(raw[:headerEnd], []byte{'\n'}) {
		line = bytes.TrimSuffix(line, []byte{'\r'})
		name, value, ok := bytes.Cut(line, []byte{':'})
		if !ok || !strings.EqualFold(strings.TrimSpace(string(name)), SyncMarkerHeader) {
			continue
		}
		if strings.TrimSpace(string(value)) == marker {
			return true
		}
	}
	return false
}

// HasSyncMarkerForTask reports whether a message was previously appended by
// the named sync routine. It prevents a destination that aliases the source
// under another hostname from feeding the routine's own copies back into it.
func HasSyncMarkerForTask(raw []byte, taskToken string) bool {
	taskToken, err := validateSyncTaskToken(taskToken)
	if err != nil {
		return false
	}
	headerEnd := len(raw)
	if i := bytes.Index(raw, []byte("\r\n\r\n")); i >= 0 {
		headerEnd = i
	} else if i := bytes.Index(raw, []byte("\n\n")); i >= 0 {
		headerEnd = i
	}
	for _, line := range bytes.Split(raw[:headerEnd], []byte{'\n'}) {
		line = bytes.TrimSuffix(line, []byte{'\r'})
		name, value, ok := bytes.Cut(line, []byte{':'})
		if !ok || !strings.EqualFold(strings.TrimSpace(string(name)), SyncMarkerHeader) {
			continue
		}
		parts := strings.Split(strings.TrimSpace(string(value)), ".")
		if len(parts) != 4 || parts[0] != "v1" || parts[1] != taskToken {
			continue
		}
		uidValidity, uidValidityErr := strconv.ParseUint(parts[2], 10, 32)
		uid, uidErr := strconv.ParseUint(parts[3], 10, 32)
		if uidValidityErr == nil && uidErr == nil && uidValidity > 0 && uid > 0 {
			return true
		}
	}
	return false
}

// SafeAppendFlags keeps portable message-state flags while dropping server-
// managed or destructive flags such as \Recent and \Deleted. Custom keywords
// are omitted because a destination may reject unsupported keywords on APPEND.
func SafeAppendFlags(flags []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, 4)
	for _, flag := range flags {
		var canonical string
		switch strings.ToLower(strings.TrimSpace(flag)) {
		case strings.ToLower(imap.SeenFlag):
			canonical = imap.SeenFlag
		case strings.ToLower(imap.AnsweredFlag):
			canonical = imap.AnsweredFlag
		case strings.ToLower(imap.FlaggedFlag):
			canonical = imap.FlaggedFlag
		case strings.ToLower(imap.DraftFlag):
			canonical = imap.DraftFlag
		}
		if canonical == "" || seen[canonical] {
			continue
		}
		seen[canonical] = true
		out = append(out, canonical)
	}
	return out
}

// FindMessageBySyncMarker finds and fetches a message previously written through
// this destination session.
func (s *SyncDestinationSession) FindMessageBySyncMarker(ctx context.Context, marker string) (syncer.FetchedMessage, bool, error) {
	if err := s.ready(ctx); err != nil {
		return syncer.FetchedMessage{}, false, err
	}
	marker, err := validateSyncMarker(marker)
	if err != nil {
		return syncer.FetchedMessage{}, false, err
	}
	criteria := imap.NewSearchCriteria()
	criteria.Header.Set(SyncMarkerHeader, marker)
	uids, err := s.client.UidSearch(criteria)
	if err != nil {
		return syncer.FetchedMessage{}, false, fmt.Errorf("search sync marker in mailbox %q: %w", s.mailbox, err)
	}
	uids = normalizeUIDList(uids)
	if len(uids) == 0 {
		return syncer.FetchedMessage{}, false, nil
	}
	// Multiple matches mean an earlier non-serialized caller appended twice. Use
	// the newest UID as the confirmed destination copy.
	fetched, err := s.fetcher.fetchOneUID(ctx, s.client, s.mailbox, uids[len(uids)-1])
	if err != nil {
		return syncer.FetchedMessage{}, false, err
	}
	return fetched, true, nil
}

// AppendMessageWithSyncMarker idempotently appends one raw message through the
// held destination connection, using a marker search before and after APPEND.
func (s *SyncDestinationSession) AppendMessageWithSyncMarker(ctx context.Context, raw []byte, marker string, date time.Time, flags []string) (syncer.FetchedMessage, error) {
	if err := s.ready(ctx); err != nil {
		return syncer.FetchedMessage{}, err
	}
	marker, err := validateSyncMarker(marker)
	if err != nil {
		return syncer.FetchedMessage{}, err
	}
	if existing, found, err := s.FindMessageBySyncMarker(ctx, marker); err != nil {
		return syncer.FetchedMessage{}, err
	} else if found {
		return existing, nil
	}
	markedRaw, err := AddSyncMarkerHeader(raw, marker)
	if err != nil {
		return syncer.FetchedMessage{}, err
	}
	appendErr := s.client.Append(s.mailbox, SafeAppendFlags(flags), date, bytes.NewReader(markedRaw))
	confirmed, found, findErr := s.FindMessageBySyncMarker(ctx, marker)
	if found && findErr == nil {
		return confirmed, nil
	}
	if appendErr != nil {
		if findErr != nil {
			return syncer.FetchedMessage{}, fmt.Errorf("append message with sync marker: %v; confirm marker: %w", appendErr, findErr)
		}
		return syncer.FetchedMessage{}, appendErr
	}
	if findErr != nil {
		return syncer.FetchedMessage{}, findErr
	}
	return syncer.FetchedMessage{}, fmt.Errorf("message was appended to mailbox %q, but sync marker %q could not be confirmed", s.mailbox, marker)
}

// FindMessageBySyncMarker is the one-shot compatibility wrapper around a short-
// lived destination session.
func (f *Fetcher) FindMessageBySyncMarker(ctx context.Context, account store.MailAccount, mailbox, marker string) (syncer.FetchedMessage, bool, error) {
	if _, err := validateSyncMarker(marker); err != nil {
		return syncer.FetchedMessage{}, false, err
	}
	session, err := f.OpenSyncDestinationSession(ctx, account, mailbox)
	if err != nil {
		return syncer.FetchedMessage{}, false, err
	}
	defer session.Close()
	return session.FindMessageBySyncMarker(ctx, marker)
}

// AppendMessageWithSyncMarker is the one-shot compatibility wrapper around a
// short-lived destination session. Large syncs should open and reuse a session.
func (f *Fetcher) AppendMessageWithSyncMarker(ctx context.Context, account store.MailAccount, mailbox string, raw []byte, marker string, date time.Time, flags []string) (syncer.FetchedMessage, error) {
	if _, err := validateSyncMarker(marker); err != nil {
		return syncer.FetchedMessage{}, err
	}
	session, err := f.OpenSyncDestinationSession(ctx, account, mailbox)
	if err != nil {
		return syncer.FetchedMessage{}, err
	}
	defer session.Close()
	return session.AppendMessageWithSyncMarker(ctx, raw, marker, date, flags)
}
